apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflowsk
spec:
  selector:
    matchLabels:
      app: mlflowsk
  template:
    metadata:
      labels:
        app: mlflowsk
    spec:
      containers:
      - name: mlflowsk
        image: mlflow_sk
        imagePullPolicy: Never
        env:
          - name: AWS_ACCESS_KEY_ID 
            value: minioadmin
          - name: AWS_SECRET_ACCESS_KEY 
            value: minioadmin
          - name: MLFLOW_S3_ENDPOINT_URL 
            value: http://minio:9000
          - name: MLFLOW_TRACKING_URI 
            value: postgresql+psycopg2://postgres:password@postgres:5432
          - name: MLFLOW_ARTIFACT_STORE 
            value: s3://mlruns
          - name: MODEL 
            value: logreg
          - name: VERSION 
            value: Staging
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 1235
      
---

apiVersion: v1
kind: Service
metadata:
  name: mlflowsk
spec:
  type: NodePort
  selector:
    app: mlflowsk
  ports:
  - port: 1235
    targetPort: 1235
    nodePort: 31235

