apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-regres-v2-infer
spec:
  selector:
    matchLabels:
      app: mlflow-regres-infer
  template:
    metadata:
      labels:
        app: mlflow-regres-infer
    spec:
      containers:
      - name: mlflow-regres-infer-v2
        image: mlflow_regres_infer:2.0
        imagePullPolicy: Never
        env:
          - name: AWS_ACCESS_KEY_ID 
            value: minioadmin
          - name: AWS_SECRET_ACCESS_KEY 
            value: minioadmin
          - name: MLFLOW_S3_ENDPOINT_URL 
            value: http://minio:9000
          - name: MLFLOW_TRACKING_URI 
            value: postgresql+psycopg2://postgres:password@postgres:5432
          - name: MLFLOW_ARTIFACT_STORE 
            value: s3://mlruns
          - name: MODEL 
            value: regres-v2.0
          - name: VERSION 
            value: Staging
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 1236