apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflowserver
spec:
  selector:
    matchLabels:
      app: mlflowserver
  template:
    metadata:
      labels:
        app: mlflowserver
    spec:
      containers:
      - name: mlflowserver
        image: mlflow_server
        imagePullPolicy: Never
        env:
          - name: AWS_ACCESS_KEY_ID 
            value: minioadmin
          - name: AWS_SECRET_ACCESS_KEY 
            value: minioadmin
          - name: MLFLOW_S3_ENDPOINT_URL 
            value: http://minio:9000
          - name: MLFLOW_TRACKING_URI 
            value: postgresql+psycopg2://postgres:password@postgres:5432
          - name: MLFLOW_ARTIFACT_STORE 
            value: s3://mlruns
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 5000
      
---

apiVersion: v1
kind: Service
metadata:
  name: mlflowserver
spec:
  type: NodePort
  selector:
    app: mlflowserver
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30005

