apiVersion: apps/v1
kind: Deployment
metadata:
  name: mltoolkit
spec:
  selector:
    matchLabels:
      app: mltoolkit
  template:
    metadata:
      labels:
        app: mltoolkit
    spec:
      containers:
      - name: mltoolkit
        image: mltoolkit
        imagePullPolicy: Never
        env:
          - name: AWS_ACCESS_KEY_ID 
            value: minioadmin
          - name: AWS_SECRET_ACCESS_KEY 
            value: minioadmin
          - name: MLFLOW_S3_ENDPOINT_URL 
            value: http://minio:9000
          - name: MLFLOW_TRACKING_URI 
            value: postgresql+psycopg2://postgres:password@postgres:5432
          - name: MLFLOW_ARTIFACT_STORE 
            value: s3://mlruns
        resources:
          requests:
            memory: "1500Mi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8000
      
---

apiVersion: v1
kind: Service
metadata:
  name: mltoolkit
spec:
  type: NodePort
  selector:
    app: mltoolkit
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30008