FROM python:3.9.5-slim
RUN pip install -U mlflow \
    && pip install psycopg2-binary \
    && pip install boto3

ENV AWS_ACCESS_KEY_ID minioadmin
ENV AWS_SECRET_ACCESS_KEY minioadmin
ENV MLFLOW_S3_ENDPOINT_URL http://172.17.0.4:9000

ENV MLFLOW_TRACKING_URI postgresql+psycopg2://postgres:password@172.17.0.2:5432
ENV MLFLOW_ARTIFACT_STORE s3://mlruns

EXPOSE 5000
CMD mlflow server --backend-store-uri ${MLFLOW_TRACKING_URI} --default-artifact-root ${MLFLOW_ARTIFACT_STORE} --host 0.0.0.0