FROM python:3.9.5-slim
RUN pip install -U dvc[s3]

ENV AWS_ACCESS_KEY_ID minioadmin
ENV AWS_SECRET_ACCESS_KEY minioadmin
ENV MLFLOW_S3_ENDPOINT_URL http://172.17.0.4:9000

CMD ["sh", "-c", "dvc remote add --global -d traindata s3://traindata \
                && dvc remote add --global -d testdata s3://testdata \
                && sleep 3600"]